export const GALVANIZE_BASE_URL = 'https://www.galvanize.com';

export const CAMPUSES = [
  { name: 'austin',
    optionName: 'Austin, TX', // used in select dropdowns
    lat: '30.26532630000001',
    lon: '-97.74954989999998',
    city: 'Austin',
    state: 'TX',
    dsi: true,
    wdi: false,
    sfdcName: 'Austin-2nd St District',
    tripleseat_location_id: 4164,
    eventServiceName: 'Galvanize Austin',
    newsletterFlagName: 'Austin_Campus_Flag__c',
    location: '2nd Street District',
    image: 'https://d1cvw29nua6zwm.cloudfront.net/campus/campus_austin.jpg',
    inputID_DMS: 'SR_BR-000061319289',
    emailID: 'ATX'
  },
  { name: 'boulder',
    optionName: 'Boulder, CO',
    lat: '40.0165447',
    lon: '-105.28168599999998',
    city: 'Boulder',
    state: 'CO',
    dsi: true,
    wdi: true,
    sfdcName: 'Boulder-Walnut St.',
    tripleseat_location_id: 3601,
    eventServiceName: 'Galvanize Boulder',
    newsletterFlagName: 'Boulder_Campus_Flag__c',
    location: 'Walnut',
    image: 'https://d1cvw29nua6zwm.cloudfront.net/campus/campus_boulder.jpg',
    inputID_DMS: 'SR_BR-000061319320',
    emailID: 'BCO'
  },
  { name: 'denver-platte',
    optionName: 'Denver, CO',
    lat: '39.75766149999999',
    lon: '-105.00695439999998',
    city: 'Denver',
    state: 'CO',
    dsi: true,
    wdi: true,
    sfdcName: 'Denver-Platte',
    tripleseat_location_id: 3600,
    eventServiceName: 'Galvanize Platte St.',
    newsletterFlagName: 'Denver_Campus_Flag__c',
    location: 'Platte',
    image: 'https://d1cvw29nua6zwm.cloudfront.net/campus/campus_denver-platte.jpg',
    inputID_DMS: 'SR_BR-000061319329',
    emailID: 'DEN'
  },
  { name: 'denver-golden-triangle',
    optionName: 'Denver, CO',
    lat: '39.733492',
    lon: '-104.9948143',
    city: 'Denver',
    state: 'CO',
    dsi: true,
    wdi: false,
    sfdcName: 'Denver-Golden Triangle',
    tripleseat_location_id: 3499,
    eventServiceName: 'Galvanize Denver Golden Triangle',
    newsletterFlagName: 'Denver_Campus_Flag__c',
    location: 'Golden Triangle',
    image: 'https://d1cvw29nua6zwm.cloudfront.net/campus/campus_denver-gt.jpg',
    inputID_DMS: 'SR_BR-000061319333',
    emailID: 'DEN-GT'
  },
  { name: 'new-york',
    optionName: 'New York, NY',
    lat: '40.7263875',
    lon: '-74.00779190000003',
    city: 'New York',
    state: 'NY',
    dsi: true,
    wdi: false,
    sfdcName: 'NYC-SoHo',
    tripleseat_location_id: 4604,
    eventServiceName: 'Galvanize NYC',
    newsletterFlagName: 'New_York_City_Campus_Flag__c',
    location: 'West SoHo',
    image: 'https://d1cvw29nua6zwm.cloudfront.net/campus/campus_nyc.jpg',
    inputID_DMS: 'SR_BR-000061319336',
    emailID: 'NYC'
  },
  { name: 'phoenix',
    optionName: 'Phoenix, AZ',
    lat: '33.439984',
    lon: '-112.066826',
    city: 'Phoenix',
    state: 'AZ',
    dsi: true,
    wdi: true,
    sfdcName: 'Phoenix-Warehouse District',
    tripleseat_location_id: 4603,
    eventServiceName: 'Galvanize Phoenix',
    newsletterFlagName: 'Phoenix_Campus_Flag__c',
    location: 'Warehouse District',
    image: 'https://s3-us-west-2.amazonaws.com/dotcom-files/phoenix-communal.jpg',
    inputID_DMS: 'SR_BR-000061319346',
    emailID: 'PHX'
  },
  { name: 'los-angeles',
    optionName: 'Los Angeles, CA',
    lat: '33.976037',
    lon: '-118.390798',
    city: 'Los Angeles',
    state: 'CA',
    dsi: true,
    wdi: true,
    sfdcName: 'Los Angeles',
    tripleseat_location_id: 8064,
    eventServiceName: 'Galvanize Los Angeles',
    newsletterFlagName: 'Los_Angeles_Campus_Flag__c',
    location: 'Los Angeles',
    image: 'https://static1.squarespace.com/static/ta/522a22cbe4b04681b0bff826/3190/assets/images/hero/hero-bg--campus-la.jpg',
    inputID_DMS: 'SR_BR-000061319330',
    emailID: 'LSA'
  },
  { name: 'san-francisco',
    optionName: 'San Francisco, CA',
    lat: '37.7875728',
    lon: '-122.39658180000004',
    city: 'San Francisco',
    state: 'CA',
    dsi: true,
    wdi: false,
    sfdcName: 'San Francisco-SoMa',
    tripleseat_location_id: 3481,
    eventServiceName: 'Galvanize San Francisco SOMA',
    newsletterFlagName: 'San_Francisco_Campus_Flag__c',
    location: 'SoMa',
    image: 'https://d1cvw29nua6zwm.cloudfront.net/campus/campus_sf.jpg',
    inputID_DMS: 'SR_BR-000061319355',
    emailID: 'SFO'
  },
  { name: 'seattle',
    optionName: 'Seattle, WA',
    lat: '47.5990943',
    lon: '-122.33370980000001',
    city: 'Seattle',
    state: 'WA',
    dsi: true,
    wdi: true,
    sfdcName: 'Seattle-Pioneer Square',
    tripleseat_location_id: 3733,
    eventServiceName: 'Galvanize Seattle',
    newsletterFlagName: 'Seattle_Campus_Flag__c',
    location: 'Pioneer Square',
    image: 'https://d1cvw29nua6zwm.cloudfront.net/campus/campus_seattle.jpg',
    inputID_DMS: 'SR_BR-000061319360',
    emailID: 'SEA'
  }
];

export const FULL_TIME_PROGRAMS = [
  {
  name:'Data Science Immersive',
  sfdcName: 'Data Science'
  },{
  name:'Software Engineering Immersive',
  sfdcName: 'Web Development'
},{
  name:'Software Engineering Remote Immersive',
  sfdcName: 'Web Development'
},{
  name:'Software Engineering Part Time Immersive',
  sfdcName: 'Web Development'
}]
